NGS/src/NGS/ContentBundle/Form/EventType.php
<?php

namespace NGS\ContentBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Translation\TranslatorInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class EventType extends AbstractType
{
    private $translator;

    public function __construct(TranslatorInterface $translator) {
        $this->translator = $translator;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('translations', 'a2lix_translations', array (
                'locales' => array('en', 'km'),
                'required_locales' => array('en'),
                'label' => false,
                'fields' => array(
                    'title' => array (
                        'field_type' => 'text',
                        'label' => $this->translator->trans('title')
                    ),
                    'description' => array (
                        'field_type' => 'ckeditor',
                        'label' => $this->translator->trans('description')
                    )
                ),
            ))
            ->add('date', 'date', array(
                'days' => range(1, 31)
            ))
            ->add('picture')
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'NGS\ContentBundle\Entity\Event'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'ngs_contentbundle_event';
    }
}

NGS/src/NGS/ContentBundle/Resources/views/abouts.html.twig
{% extends "NGSHomeBundle::home.html.twig" %}

{% block content %}
    {% for about in abouts %}
        <div class="row">
            <h3 class="art-title">{{ about.getTitle }}</h3>
            {% if about.getPicturePath is not null %}
                <img
                    src="/uploads/articles/{{ about.getPicturePath }}"
                    alt="Picture"
                    class="img-medium text-wrap"
                    align="top"
                >
            {% endif %}
            <p class="show-more-front">{{ about.getDescription|striptags }}</p>
        </div>
    {% endfor %}
{% endblock %}

NGS/src/NGS/ContentBundle/Resources/views/announcement.html.twig
{% extends "NGSHomeBundle::home.html.twig" %}

{% block content %}
    <div class="art-title">
        <h3>{{ announcement.getTitle }}</h3>
        <span class="announcement-date">{{ announcement.getDate.format('d/M/Y') }}</span>
    </div>

    {% if announcement.getPicturePath is not null %}
        <img
            src="/uploads/announcements/{{ announcement.getPicturePath }}"
            alt="Picture"
            class="img-medium text-wrap"
            align="top"
        >
    {% endif %}
    <p>{{ announcement.getDescription|striptags }}</p>
{% endblock %}

NGS/src/NGS/ContentBundle/Resources/views/announcements.html.twig
{% extends "NGSHomeBundle::home.html.twig" %}

{% block content %}
    {% for announcement in announcements %}
        <div class="row">
            <div class="art-title">
                <h3>{{ announcement.getTitle }}</h3>
                <span class="announcement-date">{{ announcement.getDate.format('d/M/Y') }}</span>
            </div>
            {% if announcement.getPicturePath is not null %}
                <img
                    src="/uploads/announcements/{{ announcement.getPicturePath }}"
                    alt="Picture"
                    class="img-medium text-wrap"
                    align="top"
                >
            {% endif %}
            <p class="show-more-front">{{ announcement.getDescription|striptags }}</p>
        </div>
    {% endfor %}
{% endblock %}

NGS/src/NGS/ContentBundle/Resources/views/article.html.twig
{% extends "NGSHomeBundle::home.html.twig" %}

{% block content %}
    <h3 class="art-title">{{ article.getTitle }}</h3>
    {% if article.getPicturePath is not null %}
        <img
            src="/uploads/articles/{{ article.getPicturePath }}"
            alt="Picture"
            class="img-medium text-wrap"
            align="top"
        >
    {% endif %}
    <p>{{ article.getDescription|striptags }}</p>
{% endblock %}

NGS/src/NGS/ContentBundle/Resources/views/contact.html.twig
{% extends "NGSHomeBundle::home.html.twig" %}

{% block content %}

{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

    <div class="row form-group">
        <div class="col-md-2">{{ form_label(form.name) }}</div>
        <div class="col-md-10">
            {{ form_widget(form.name, {'attr':{'class': 'form-control'}}) }}
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2">{{ form_label(form.email) }}</div>
        <div class="col-md-10">
            {{ form_widget(form.email, {'attr':{'class': 'form-control'}}) }}
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2">{{ form_label(form.subject) }}</div>
        <div class="col-md-10">
            {{ form_widget(form.subject, {'attr':{'class': 'form-control'}}) }}
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2">{{ form_label(form.body) }}</div>
        <div class="col-md-10">
            {{ form_widget(form.body, {'attr':{'class': 'form-control'}}) }}
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2"></div>
        <div class="col-md-10 buttons">
            {{ form_widget(form.send, {'attr':{'class': 'btn btn-primary'}}) }}
        </div>
    </div>

{{ form_end(form) }}
{% endblock %}

NGS/src/NGS/ContentBundle/Resources/views/contactBooks.html.twig
{% extends "NGSHomeBundle::home.html.twig" %}

{% block content %}
    <table>
        <tr>
            <th>{{ 'logo'|trans }}</th>
            <th>{{ 'name'|trans }}</th>
            <th>{{ 'description'|trans }}</th>
            <th>{{ 'company_name'|trans }}</th>
            <th>{{ 'phone'|trans }}</th>
            <th>{{ 'email'|trans }}</th>
            <th>{{ 'address'|trans }}</th>
            <th>{{ 'website'|trans }}</th>
            <th>{{ 'facebook' }}</th>
            <th>{{ 'section'|trans }}</th>
        </tr>
    {% for contactBook in contactBooks %}
        <tr>
            <td style="text-align: center"><img src="/uploads/contact_books/{{ contactBook.getPicturePath }}" class="img-thumb"></td>
            <td>{{ contactBook.getTitle }}</td>
            <td class="show-more-front">{{ contactBook.getDescription|striptags }}</td>
            <td>{{ contactBook.getCompanyName }}</td>
            <td>{{ contactBook.getPhone }}</td>
            <td>{{ contactBook.getEmail }}</td>
            <td>{{ contactBook.getAddress }}</td>
            <td>{{ contactBook.getWebsite }}</td>
            <td>{{ contactBook.getFacebook }}</td>
            <td>{{ contactBook.getSection }}</td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

NGS/src/NGS/ContentBundle/Resources/views/event.html.twig
{% extends "NGSHomeBundle::home.html.twig" %}

{% block content %}
    <div class="art-title">
        <h3>{{ event.getTitle }}</h3>
        <span class="event-date">{{ event.getDate.format('d/M/Y') }}</span>
    </div>
	{% if event.getPicturePath is not null %}
        <img
            src="/uploads/events/{{ event.getPicturePath }}"
            alt="Picture"
            class="img-medium text-wrap"
            align="top"
        >
    {% endif %}
    <p>{{ event.getDescription|striptags }}</p>
{% endblock %}

NGS/src/NGS/ContentBundle/Resources/views/events.html.twig
{% extends "NGSHomeBundle::home.html.twig" %}

{% block content %}
    {% for event in events %}
        <div class="row">
            <div class="art-title">
                <h3>{{ event.getTitle }}</h3>
                <span class="event-date">{{ event.getDate.format('d/M/Y') }}</span>
            </div>
            {% if event.getPicturePath is not null %}
                <img
                    src="/uploads/events/{{ event.getPicturePath }}"
                    alt="Picture"
                    class="img-medium text-wrap"
                    align="top"
                >
            {% endif %}
            <p class="show-more-front">{{ event.getDescription|striptags }}</p>
        </div>
    {% endfor %}
{% endblock %}

NGS/src/NGS/ContentBundle/Resources/views/index.html.twig
{% extends "NGSHomeBundle::home.html.twig" %}

{% block content %}
    {% for event in events %}
        <div class="row">
            <div class="event-title">
                <h3>{{ event.getTitle }}</h3>
                <span class="event-date">{{ event.getDate.format('d/M/Y') }}</span>
            </div>
            <p>{{ event.getDescription|striptags }}</p>
        </div>
    {% endfor %}
{% endblock %}

NGS/src/NGS/ContentBundle/Resources/views/libraries.html.twig
{% extends "NGSHomeBundle::home.html.twig" %}

{% block content %}
    <table>
        <tr class="row">
            <th class="col-md-2">{{ 'cover'|trans }}</th>
            <th class="col-md-2">{{ 'title'|trans }}</th>
            <th class="col-md-2">{{ 'author'|trans }}</th>
            <th class="col-md-3">{{ 'description'|trans }}</th>
            <th class="col-md-1">{{ 'read'|trans }}</th>
            <th class="col-md-2">{{ 'download'|trans }}</th>
        </tr>
    {% for library in libraries %}
        <tr class="row">
            <td class="col-md-2"><img src="/uploads/libraries/{{ library.getPicturePath }}" alt="Cover" class="thumb-ebook"></td>
            <td class="col-md-2">{{ library.getTitle }}</td>
            <td class="col-md-2">{{ library.getAuthor }}</td>
            <td class="show-more col-md-3">{{ library.getDescription|striptags }}</td>
            <td class="col-md-1">
                <a
                    href="{{ path('ngs_library_read', {filename: library.filePath}) }}"
                >
                    {{ 'read'|trans }}
                </a>
            </td>
            <td class="col-md-2">
            {% if library.isDownloadable == true %}
                <a
                    href="{{ path('ngs_library_download', {filename: library.filePath}) }}"
                >
                    {{ 'download'|trans }}
                </a>
            {% endif %}
            </td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

NGS/src/NGS/ContentBundle/Resources/views/read.html.twig
<iframe
    src="{{ asset('uploads/libraries/' ~ filename) }}#toolbar=0" 
    style="width:100%; height:100%;"
    frameborder="0"
>
</iframe>

NGS/src/NGS/ContentBundle/Resources/views/services.html.twig
{% extends "NGSHomeBundle::home.html.twig" %}

{% block content %}
    {% for service in services %}
        <div class="row">
            <h3 class="art-title">{{ service.getTitle }}</h3>
            {% if service.getPicturePath is not null %}
                <img
                    src="/uploads/articles/{{ service.getPicturePath }}"
                    alt="Picture"
                    class="img-medium text-wrap"
                    align="top"
                >
            {% endif %}
            <p class="show-more-front">{{ service.getDescription|striptags }}</p>
        </div>
    {% endfor %}
{% endblock %}